urls.py
from handlers import account, member, node, topic, dashboard, others, api

__all__ = ['handlers', 'ui_modules']

handlers = []
handlers.extend(account.handlers)
handlers.extend(member.handlers)
handlers.extend(node.handlers)
handlers.extend(topic.handlers)
handlers.extend(dashboard.handlers)
handlers.extend(others.handlers)
handlers.extend(api.handlers)

ui_modules = {}
ui_modules.update(**node.ui_modules)
ui_modules.update(**topic.ui_modules)

gather/account/forms.py
# -*- coding:utf-8 -*-

from __future__ import unicode_literals

from flask import current_app, g, render_template, url_for
from flask.ext.mail import Message
from gather.form import Form
from wtforms import TextField, PasswordField, TextAreaField, BooleanField
from wtforms.validators import Length, Email, DataRequired, Optional, URL, Regexp
from gather.utils import send_mail
from gather.account.models import Account
from gather.account.utils import login_user, create_reset_token


class LoginForm(Form):
    username = TextField("用户名", validators=[
        Length(max=15, message="用户名最多15个字符哟~"),
        DataRequired(),
        Regexp("^[a-zA-Z0-9]+$", message="用户名只能由英文字母和数字构成")
    ])
    password = PasswordField("密码", validators=[
        DataRequired()
    ])

    def validate_password(self, field):
        account = self.username.data
        user = Account.query.filter_by(username=account).first()

        if user and user.check_password(field.data):
            self.user = user
            return user
        raise ValueError("用户名或密码错误")

    def login(self):
        login_user(self.user)


class RegisterForm(LoginForm):
    email = TextField("电子邮件地址", validators=[
        Email(),
        DataRequired()
    ])

    def validate_password(self, field):
        return True

    def validate_username(self, field):
        if Account.query.filter_by(username=field.data.lower()).count():
            raise ValueError("这个用户名被注册了")

    def validate_email(self, field):
        if Account.query.filter_by(email=field.data.lower()).count():
            raise ValueError("这个电子邮件地址被注册了")

    def save(self):
        user = Account(**self.data)
        return user.save()


class FindForm(Form):
    email = TextField("电子邮件地址", validators=[
        Email(),
        DataRequired()
    ])

    def validate_email(self, field):
        if not Account.query.filter_by(email=field.data.lower()).count():
            raise ValueError("这个电子邮件地址尚未注册")

    def send(self):
        config = current_app.config
        email = self.email.data
        user = Account.query.filter_by(email=email.lower()).first_or_404()
        msg = Message(
            "找回 {username} 在 {site_name} 的密码".format(
                username=user.username,
                site_name=config["FORUM_TITLE"]
            ),
            recipients=[email],
        )
        reset_url = "".join([
            config["FORUM_URL"].rstrip("/"),
            url_for("account.reset"),
            "?token=",
            create_reset_token(user)
        ])
        msg.html = render_template('email/reset.html', user=user, url=reset_url)
        send_mail(msg)


class ResetForm(Form):
    password = PasswordField("密码", validators=[
        DataRequired()
    ])

    def reset(self, user):
        user.change_password(self.password.data)
        return user.save()


class SettingsForm(Form):
    username = TextField("用户名", validators=[
        Length(max=15, message="用户名最多15个字符哟~"),
        DataRequired(),
        Regexp("^[a-zA-Z0-9]+$", message="用户名只能由英文字母和数字构成")
    ])
    website = TextField("网站", validators=[
        URL(), Optional(), Length(max=100)
    ])
    email = TextField("电子邮件地址", validators=[
        Email(),
        DataRequired()
    ])
    feeling_lucky = BooleanField("手气不错")
    description = TextAreaField("简介", validators=[
        Optional(), Length(max=500)
    ], description="我叫王大锤，万万没想到..")
    css = TextAreaField("自定义 CSS", validators=[
        Optional()
    ], description="body{display: none}")

    def validate_username(self, field):
        user = Account.query.filter_by(username=field.data.lower()).first()
        if user and user.id != g.user.id:
            raise ValueError("这个用户名被注册了")

    def validate_email(self, field):
        user = Account.query.filter_by(email=field.data.lower()).first()
        if user and user.id != g.user.id:
            raise ValueError("这个电子邮件地址被注册了")

    def save(self):
        user = Account.query.get(g.user.id)
        self.populate_obj(user)
        user.save()

gather/node/forms.py
# -*- coding:utf-8 -*-

from __future__ import unicode_literals

from gather.form import Form
from wtforms import TextField, TextAreaField
from wtforms.validators import DataRequired, Optional, Length, URL
from .models import Node


class ChangeNodeForm(Form):
    name = TextField("节点名称", validators=[
        DataRequired()
    ])
    slug = TextField("Slug", validators=[
        DataRequired()
    ], description="就是会出现在 URL 里面的那坨字母~"
    )
    description = TextAreaField("简介", validators=[
        Optional(), Length(max=500)
    ], description="喵")
    icon = TextField("节点图标", validators=[
        Optional(), URL()
    ])

    def validate_parent_node(self, field):
        if field.data and field.data == self.obj:
            raise ValueError("父节点不能是自己= =")

    def save(self):
        node = self.obj
        self.populate_obj(node)
        return node.save()


class CreateNodeForm(ChangeNodeForm):
    def validate_name(self, field):
        if Node.query.filter_by(name=field.data.lower()).count():
            raise ValueError("这个节点名被注册了")

    def validate_slug(self, field):
        if Node.query.filter_by(slug=field.data.lower()).count():
            raise ValueError("这个 Slug 被注册了")

    def create(self):
        node = Node(**self.data)
        self.node = node
        return node.save()

gather/topic/forms.py
# -*- coding:utf-8 -*-

from __future__ import unicode_literals

from datetime import datetime
from flask import g
from gather.form import Form
from wtforms import TextField, TextAreaField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import Required, Optional, Length
from ghdiff import diff
from gather.node.models import Node
from .models import Topic, Reply, History


class CreateTopicForm(Form):
    node = QuerySelectField(
        "节点",
        validators=[Required()],
        query_factory=Node.query_all,
        get_pk=lambda a: a.id,
        get_label=lambda a: a.name
    )
    title = TextField("标题", validators=[
        Required(),
        Length(max=100)
    ])
    content = TextAreaField("正文", validators=[Optional()])

    def create(self):
        topic = Topic(
            **self.data
        )
        return topic.save()


class ChangeTopicForm(CreateTopicForm):
    def save(self, topic):
        if self.title.data != topic.title:
            title = self.title.data
            history = History(
                diff_content="将标题从 %s 修改为 %s" % (topic.title, title),
                topic=topic,
                author=g.user
            )
            history.save()
            topic.title = title
        if self.node.data != topic.node:
            node = self.node.data
            history = History(
                diff_content="从 %s 移动到 %s" % (topic.node.name, node.name),
                topic=topic,
                author=g.user
            )
            history.save()
            topic.node = node
        if self.content.data != topic.content:
            content = self.content.data
            history = History(
                diff_content=diff(topic.content, content, css=False),
                topic=topic,
                author=g.user
            )
            history.save()
            topic.content = content
        topic.changed = datetime.utcnow()
        return topic.save()


class ReplyForm(Form):
    content = TextAreaField("正文", [
        Required(),
        Length(max=10000),
    ])

    def create(self, topic):
        reply = Reply(
            content=self.content.data,
            topic=topic,
            author=g.user
        )
        return reply.save()


class ChangeReplyForm(ReplyForm):
    def save(self, reply):
        if self.content.data != reply.content:
            content = self.content.data
            history = History(
                diff_content=diff(reply.content, content, css=False),
                reply=reply,
                author=g.user
            )
            history.save()
            reply.content = content
        return reply.save()

gather/account/views.py
# -*- coding:utf-8 -*-

from flask import Blueprint, abort
from flask import request, url_for
from flask import g, render_template, redirect
from gather.account.forms import (LoginForm, RegisterForm,
                                  FindForm, ResetForm, SettingsForm)
from gather.account.utils import require_login, login_user, logout_user, verify_reset_token
from gather.utils import require_token

bp = Blueprint("account", __name__, url_prefix="/account")


@bp.route("/login", methods=("GET", "POST"))
def login():
    next_url = request.args.get('next', "/")
    form = LoginForm()
    if form.validate_on_submit():
        form.login()
        return redirect(next_url)
    return render_template("account/login.html", form=form)


@bp.route("/register", methods=("GET", "POST"))
def register():
    next_url = request.args.get('next', url_for('.settings'))
    form = RegisterForm()
    if form.validate_on_submit():
        user = form.save()
        login_user(user)
        return redirect(next_url)
    return render_template("account/register.html", form=form)


@bp.route("/logout/<token>")
@require_login
@require_token
def logout():
    next_url = request.args.get('next', "/")
    logout_user()
    return redirect(next_url)


@bp.route("/find", methods=("GET", "POST"))
def find_password():
    if g.user:
        return redirect("/")
    form = FindForm()
    if form.validate_on_submit():
        form.send()
        return render_template("account/find_sent.html")
    return render_template("account/find_password.html", form=form)


@bp.route("/reset", methods=("GET", "POST"))
def reset():
    token = request.args.get("token", None)
    user = verify_reset_token(token)
    if not user:
        return abort(403)
    form = ResetForm()
    if form.validate_on_submit():
        user = form.reset(user)
        login_user(user)
        return redirect("/")
    return render_template("account/reset.html", form=form)


@bp.route("/settings", methods=("GET", "POST"))
@require_login
def settings():
    user = g.user
    form = SettingsForm(obj=user)
    next_url = request.args.get('next', url_for('.settings'))
    if form.validate_on_submit():
        form.save()
        return redirect(next_url)
    return render_template('account/settings.html', form=form)

gather/admin/views.py
# -*- coding:utf-8 -*-

from flask import Blueprint

bp = Blueprint("admin", __name__, url_prefix="/admin")

gather/frontend/views.py
# -*- coding:utf-8 -*-

from flask import Blueprint, render_template, make_response

bp = Blueprint("frontend", __name__, url_prefix="")


@bp.route("/")
def index():
    from gather.topic.models import Topic
    topics = Topic.query.order_by(Topic.updated.desc()).limit(5)
    return render_template("index.html", topics=topics)


@bp.route("/feed")
def feed():
    from gather.topic.models import Topic
    topics = Topic.query.order_by(Topic.updated.desc()).limit(15)
    response = make_response(render_template("feed.xml", topics=topics))
    response.mimetype = "application/atom+xml"
    return response

gather/node/views.py
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import render_template, redirect, url_for

from gather.account.utils import require_staff
from .forms import CreateNodeForm, ChangeNodeForm
from .models import Node

bp = Blueprint("node", __name__, url_prefix="/node")


@bp.route("/")
def index():
    items = Node.query_all()
    return render_template("node/index.html", items=items)


@bp.route("/create", methods=("GET", "POST"))
@require_staff
def create():
    form = CreateNodeForm()
    if form.validate_on_submit():
        print "validate"
        form.create()
        return redirect(url_for(".node", slug=form.node.slug))
    else:
        print form.errors
    return render_template("node/create.html", form=form)


@bp.route("/<slug>", defaults={'page': 1})
@bp.route("/<slug>/page/<int:page>")
def node(slug, page):
    from gather.topic.models import Topic
    node = Node.query.filter_by(slug=slug).first_or_404()
    topics = Topic.query.filter_by(node=node)
    paginator = topics.order_by(Topic.updated.desc()).paginate(page)
    return render_template("node/node.html", node=node, paginator=paginator)


@bp.route("/<slug>/change", methods=("GET", "POST"))
def change(slug):
    node = Node.query.filter_by(slug=slug).first_or_404()
    form = ChangeNodeForm(obj=node)
    if form.validate_on_submit():
        form.save()
        return redirect(url_for(".node", slug=node.slug))
    return render_template("node/change.html", form=form)

gather/topic/views.py
# -*- coding:utf-8 -*-

from flask import Blueprint
from flask import url_for, g, redirect, render_template, abort, request
from gather.utils import require_token
from gather.account.utils import require_login, require_staff, require_admin
from gather.node.models import Node
from .forms import CreateTopicForm, ChangeTopicForm, ReplyForm, ChangeReplyForm
from .models import Topic, Reply

bp = Blueprint("topic", __name__, url_prefix="/topic")


@bp.route("/", defaults={'page': 1})
@bp.route('/page/<int:page>')
def index(page):
    paginator = Topic.query.order_by(Topic.created.desc()).paginate(page)
    return render_template('topic/index.html', paginator=paginator)


@bp.route("/create", methods=("GET", "POST"))
@require_login
def create():
    form = CreateTopicForm()
    if "node" in request.args:
        try:
            nid = int(request.args.get("node"))
        except ValueError:
            pass
        else:
            form.node.data = Node.query.get_or_404(nid)
    if form.validate_on_submit():
        topic = form.create()
        return redirect(url_for(".topic", topic_id=topic.id))
    return render_template("topic/create.html", form=form)


@bp.route("/<int:topic_id>", methods=("GET", "POST"), defaults={'page': 1})
@bp.route("/<int:topic_id>/page/<int:page>", methods=("GET", "POST"))
def topic(topic_id, page):
    topic = Topic.query.get_or_404(topic_id)
    form = ReplyForm()
    if g.user and form.validate_on_submit():
        form.create(topic=topic)
        return redirect(url_for(".topic", topic_id=topic.id, page=topic.last_page))
    replies = Reply.query.filter_by(topic=topic).order_by(Reply.id.asc())
    paginator = replies.paginate(page)
    if g.user:
        topic.mark_read(g.user)
    return render_template(
        "topic/topic.html", topic=topic, form=form,
        paginator=paginator
    )


@bp.route("/<int:topic_id>/remove/<token>")
@require_admin
@require_token
def remove_topic(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    topic.delete()
    return redirect("/")


@bp.route("/<int:topic_id>/change", methods=("GET", "POST"))
@require_staff
def change_topic(topic_id):
    topic = Topic.query.get_or_404(topic_id)
    form = ChangeTopicForm(obj=topic)
    if form.validate_on_submit():
        topic = form.save(topic=topic)
        return redirect(url_for(".topic", topic_id=topic.id))
    return render_template("topic/change.html", form=form)


@bp.route("/<int:topic_id>/<int:reply_id>/change", methods=("GET", "POST"))
@require_staff
def change_reply(topic_id, reply_id):
    topic = Topic.query.get_or_404(topic_id)
    reply = Reply.query.get_or_404(reply_id)
    if reply.topic != topic:
        abort(233)
    form = ChangeReplyForm(obj=reply)
    if form.validate_on_submit():
        form.save(reply=reply)
        return redirect(url_for(".topic", topic_id=topic.id))
    return render_template("topic/change_reply.html", form=form)

gather/user/views.py
# -*- coding:utf-8 -*-

from flask import Blueprint, redirect, url_for
from flask import render_template

from gather.utils import require_token
from gather.account.models import db, Account
from gather.account.utils import require_admin
from gather.topic.models import Topic

bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("/", defaults={'page': 1})
@bp.route('/page/<int:page>')
def index(page):
    accounts = Account.query.order_by(Account.id.desc())
    paginator = accounts.paginate(page, per_page=18)
    return render_template("user/index.html", paginator=paginator)


@bp.route("/<name>")
def profile(name):
    user = Account.query.filter_by(username=name).first_or_404()
    topics = Topic.query.filter_by(author=user).order_by(Topic.id.desc())[:5]
    return render_template("user/profile.html", user=user, topics=topics)


@bp.route("/<name>/topic", defaults={'page': 1})
@bp.route('/<name>/topic/page/<int:page>')
def topic(name, page):
    user = Account.query.filter_by(username=name).first_or_404()
    paginator = Topic.query.filter_by(author=user).\
        order_by(Topic.created.desc()).paginate(page)
    return render_template('user/topic.html', user=user, paginator=paginator)


@bp.route("/<name>/promote/<token>")
@require_admin
@require_token
def promote(name):
    user = Account.query.filter_by(username=name).first_or_404()
    user.role = "staff"
    db.session.add(user)
    db.session.commit()
    return redirect(url_for(".profile", name=user.username))


@bp.route("/<name>/demote/<token>")
@require_admin
@require_token
def demote(name):
    user = Account.query.filter_by(username=name).first_or_404()
    user.role = "user"
    db.session.add(user)
    db.session.commit()
    return redirect(url_for(".profile", name=user.username))

gather/templates/topic/change.html
{% extends "layout.html" %}

{% block title %}修改话题{% endblock %}

{% from "snippet/nav.html" import navigation %}
{% block nav %}{{ navigation('topic') }}{% endblock %}

{% block content %}
  {% from "snippet/form.html" import form_field %}
  <div class="signal-form">
      <header>修改话题</header>
      <form method="post" action="">
        {{ form.csrf_token }}
        {{ form_field(form.node) }}
        {{ form_field(form.title) }}
        {{ form_field(form.content) }}
        <div class="form-controls">
          <button type="submit">修改</button>
        </div>
      </form>
  </div>
{% endblock %}

gather/templates/topic/change_reply.html
{% extends "layout.html" %}

{% block title %}修改回复{% endblock %}

{% from "snippet/nav.html" import navigation %}
{% block nav %}{{ navigation('topic') }}{% endblock %}

{% block content %}
  {% from "snippet/form.html" import form_field %}
  <div class="signal-form">
      <header>修改回复</header>
      <form method="post" action="">
        {{ form.csrf_token }}
        {{ form_field(form.content) }}
        <div class="form-controls">
          <button type="submit">修改</button>
        </div>
      </form>
  </div>
{% endblock %}

gather/templates/topic/create.html
{% extends "layout.html" %}

{% block title %}新建话题{% endblock %}

{% from "snippet/nav.html" import navigation %}
{% block nav %}{{ navigation('topic') }}{% endblock %}

{% block content %}
  {% from "snippet/form.html" import form_field, select_field %}
  <div class="signal-form">
      <header>新建话题</header>
      <form method="post" action="">
        {{ form.csrf_token }}
        {{ form_field(form.node) }}
        {{ form_field(form.title) }}
        {{ form_field(form.content) }}
        <div class="form-controls">
          <button type="submit">新建</button>
        </div>
      </form>
  </div>
{% endblock %}

gather/templates/topic/index.html
{% extends "layout.html" %}

{% block title %}话题列表{% endblock %}

{% from "snippet/nav.html" import navigation %}
{% block nav %}{{ navigation('topic') }}{% endblock %}

{% block main %}
  <div class="card">
    <header>话题列表</header>
    {% from "snippet/topic.html" import topic_list %}
    {{ topic_list(paginator.items) }}

    <footer>
      {% from "snippet/pagination.html" import pagination %}
      {{ pagination(paginator, url_for(".index")) }}
    </footer>
  </div>
{% endblock %}

gather/templates/topic/topic.html
{% extends "layout.html" %}

{% block title %}{{ topic.title }}{% endblock %}

{% from "snippet/nav.html" import navigation %}
{% block nav %}{{ navigation('topic') }}{% endblock %}

{% block head %}
<meta name="description" content="作者： {{ topic.author.username }} <br />{{ topic.content }}" />
{% endblock %}

{% block main %}
  <div class="card">
    <header>
      {{ topic.title }}
      {% if g.user and g.user.is_staff %}
        <div id="topic-control">
          <a href="{{ url_for('.change_topic', topic_id=topic.id) }}"><i class="icon-edit"></i></a>
          {% if g.user.is_admin %}
            <a href="{{ url_for_with_token('.remove_topic', topic_id=topic.id) }}"><i class="icon-remove"></i></a>
          {% endif %}
        </div>
      {% endif %}
    </header>
    {% if topic.content %}
      <div>
        {{ topic.content|content_to_html }}
      </div>
    {% endif %}
    <footer>
      {% from "snippet/topic.html" import topic_info %}
      {{ topic_info(topic) }}
    </footer>
  </div>
  {% if paginator.items %}
    {% set floor_num = (paginator.page - 1) * paginator.per_page + 1 %}
    <div class="card">
      {% for reply in paginator.items %}
        {% set author_url = url_for("user.profile", name=reply.author.username) %}
        <div class="reply-list" data-floor="{{ floor_num }}" id="reply_{{ floor_num }}">
          <a href="{{ author_url }}">
            <img src="{{ reply.author.avatar(48) }}" class="avatar" alt="{{ reply.author.username }}"/>
          </a>
          <span class="reply-floor">#{{ floor_num }}</span>
          <div class="reply-control">
            {% if reply.content|length < 50 %}
              <a href="#" class="duixing-this-floor" data-content="{{ reply.content }}">队形</a>
            {% endif %}
            <a href="#" class="reply-this-floor" data-floor="{{ floor_num }}" data-user="{{ reply.author.username }}">
              @
            </a>
            {% if g.user and g.user.is_staff %}
              <a href="{{ url_for('.change_reply', topic_id=topic.id, reply_id=reply.id) }}"><i class="icon-edit"></i></a>
            {% endif %}
          </div>
          <div class="reply-info">
            <div class="reply-meta">
              <a href="{{ author_url }}" class="user-link">{{ reply.author.username }}</a> <span>发布于</span>
              <time datetime="{{ reply.created|xmldatetime }}"></time>
              {% if reply.changed %}
              | <span>修改于</span> <time datetime="{{ reply.changed|xmldatetime }}"></time>
              {% endif %}
            </div>
            <div class="reply-content">
              {{ reply.content|content_to_html }}
            </div>
          </div>
        </div>
        {% set floor_num = floor_num + 1 %}
      {% endfor %}
      <footer>
        {% from "snippet/pagination.html" import pagination %}
        {{ pagination(paginator, url_for(".topic", topic_id=topic.id)) }}
      </footer>
    </div>
  {% endif %}
  {% if g.user %}
  <div class="card">
    <header>回复</header>
    {% from "snippet/form.html" import form_field %}
    <form action="{{ url_for('.topic', topic_id=topic.id) }}" method="post">
      {{ form.csrf_token }}
      {{ form.content }}
      <div class="form-controls">
        <button type="submit">回复</button>
      </div>
    </form>
  </div>
  {% endif %}
{% endblock %}

{% block sidebar %}
  {% from "snippet/sidebar.html" import user_sidebar, node_sidebar %}
  {{ user_sidebar(topic.author) }}
  {{ node_sidebar(topic.node) }}
{% endblock %}